import type { Metadata } from "next";
import {
	Figtree,
	Geist,
	Geist_Mono,
	Inter,
	Noto_Serif, Raleway, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";

const ibmPlexSansHeading = IBM_Plex_Sans({subsets:['latin'],variable:'--font-heading'});

const notoSerif = Noto_Serif({ subsets: ["latin"], variable: "--font-serif" });

const raleway = Raleway({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Mail Service",
	description: "Generated by Bagus Sudrajat @kentoes",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn(
        				"h-full",
        				"antialiased",
        				geistSans.variable,
        				geistMono.variable, notoSerif.variable, "font-sans", raleway.variable, ibmPlexSansHeading.variable)}
		>
			<body className="min-h-full flex flex-col">
				<TooltipProvider>{children}</TooltipProvider>
			</body>
		</html>
	);
}
