import type { Metadata } from "next";
import { Geist, Geist_Mono, Lora, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

const loraHeading = Lora({ subsets: ["latin"], variable: "--font-heading" });

const sourceSans3 = Source_Sans_3({
	subsets: ["latin"],
	variable: "--font-sans",
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn(
				"h-full",
				"antialiased",
				geistSans.variable,
				geistMono.variable,
				"font-sans",
				sourceSans3.variable,
				loraHeading.variable,
			)}
		>
			<body className="min-h-full flex flex-col">
				<TooltipProvider>{children}</TooltipProvider>
				<Toaster richColors position="top-right" />
			</body>
		</html>
	);
}
