import type { Metadata } from "next";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import "./globals.css";
import { Inter, Noto_Sans, Source_Sans_3, Merriweather, Public_Sans, Figtree, Geist } from "next/font/google";

const merriweatherHeading = Merriweather({subsets:['latin'],variable:'--font-heading'});

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn(
        				"h-full",
        				"antialiased"
        			, "font-sans", figtree.variable, merriweatherHeading.variable)}
		>
			<body className="min-h-full flex flex-col">
				<TooltipProvider>{children}</TooltipProvider>
				<Toaster richColors position="top-right" />
			</body>
		</html>
	);
}
