import type {
	FolderCounterDto,
	MailDetailDto,
	MailFolderDto,
	MailSummaryDto,
} from "@/types/mail";

export const DUMMY_FOLDERS: MailFolderDto[] = [
	{
		id: "eoffice-mailbox",
		parentFolderId: null,
		ownerId: "system",
		name: "eOffice Mailbox",
		iconCls: "icon-mailbox",
		system: true,
		unread: 347,
		total: 1000,
	},
	{
		id: "inbox",
		parentFolderId: "eoffice-mailbox",
		ownerId: "system",
		name: "Inbox",
		iconCls: "icon-inbox",
		system: true,
		unread: 314,
		total: 500,
	},
	{
		id: "draft",
		parentFolderId: "eoffice-mailbox",
		ownerId: "system",
		name: "Draft",
		iconCls: "icon-draft",
		system: true,
		unread: 1,
		total: 5,
	},
	{
		id: "read-items",
		parentFolderId: "eoffice-mailbox",
		ownerId: "system",
		name: "Read Items",
		iconCls: "icon-read",
		system: true,
		unread: 32,
		total: 200,
	},
	{
		id: "sent-items",
		parentFolderId: "eoffice-mailbox",
		ownerId: "system",
		name: "Sent Items",
		iconCls: "icon-sent",
		system: true,
		unread: 0,
		total: 239,
	},
	{
		id: "deleted-items",
		parentFolderId: "eoffice-mailbox",
		ownerId: "system",
		name: "Deleted Items",
		iconCls: "icon-delete",
		system: true,
		unread: 0,
		total: 131,
	},
	{
		id: "personal-folder",
		parentFolderId: null,
		ownerId: "user",
		name: "Personal Folder",
		iconCls: "icon-folder",
		system: false,
		unread: 66,
		total: 200,
	},
	{
		id: "penting",
		parentFolderId: "personal-folder",
		ownerId: "user",
		name: "penting",
		iconCls: "icon-folder",
		system: false,
		unread: 9,
		total: 20,
	},
	{
		id: "finish-project",
		parentFolderId: "personal-folder",
		ownerId: "user",
		name: "finish-project",
		iconCls: "icon-folder",
		system: false,
		unread: 2,
		total: 10,
	},
	{
		id: "original-data",
		parentFolderId: "personal-folder",
		ownerId: "user",
		name: "Original Data",
		iconCls: "icon-folder",
		system: false,
		unread: 0,
		total: 5,
	},
	{
		id: "slip",
		parentFolderId: "personal-folder",
		ownerId: "user",
		name: "slip",
		iconCls: "icon-folder",
		system: false,
		unread: 48,
		total: 100,
	},
	{
		id: "kgb",
		parentFolderId: "personal-folder",
		ownerId: "user",
		name: "kgb",
		iconCls: "icon-folder",
		system: false,
		unread: 1,
		total: 2,
	},
	{
		id: "pks-webservice",
		parentFolderId: "personal-folder",
		ownerId: "user",
		name: "PKS Webservice",
		iconCls: "icon-folder",
		system: false,
		unread: 1,
		total: 3,
	},
	{
		id: "update-tarif",
		parentFolderId: "personal-folder",
		ownerId: "user",
		name: "update-tarif",
		iconCls: "icon-folder",
		system: false,
		unread: 1,
		total: 5,
	},
	{
		id: "perdir",
		parentFolderId: "personal-folder",
		ownerId: "user",
		name: "perdir",
		iconCls: "icon-folder",
		system: false,
		unread: 2,
		total: 4,
	},
	{
		id: "pks-langganan",
		parentFolderId: "personal-folder",
		ownerId: "user",
		name: "PKS Langganan",
		iconCls: "icon-folder",
		system: false,
		unread: 0,
		total: 2,
	},
	{
		id: "peraturan",
		parentFolderId: "personal-folder",
		ownerId: "user",
		name: "peraturan",
		iconCls: "icon-folder",
		system: false,
		unread: 1,
		total: 3,
	},
];

export const DUMMY_MAILS: MailSummaryDto[] = [
	{
		id: "mail-1",
		mailNumber: "001/ND/DIR/IV/2026",
		mailDate: "2026-04-15T08:00:00Z",
		subject: "Undangan Rapat Koordinasi Bulanan April",
		audit: {
			createdBy: "user-1",
			createdByName: "Sekretaris Direksi",
			createdDate: "2026-04-15T08:00:00Z",
			updatedDate: "2026-04-15T08:00:00Z",
		},
		summary: {
			attachmentQty: 1,
			toStr: "Para Manager",
		},
		readStatus: 0,
		status: "SENT",
		folderId: "inbox",
		type: { id: "INTERNAL", name: "Internal" },
		category: { id: "ND", name: "Nota Dinas" },
		circulationName: "Disposisi",
		maxResponseDate: "2026-04-20T17:00:00Z",
		thread: { rootMailId: null, parentMailId: null },
		totalCount: 10,
	},
	{
		id: "mail-2",
		mailNumber: "002/U/HRD/IV/2026",
		mailDate: "2026-04-14T10:30:00Z",
		subject: "Pengumuman Libur Hari Raya",
		audit: {
			createdBy: "user-2",
			createdByName: "Kepala HRD",
			createdDate: "2026-04-14T10:30:00Z",
			updatedDate: "2026-04-14T10:30:00Z",
		},
		summary: {
			attachmentQty: 0,
			toStr: "Seluruh Karyawan",
		},
		readStatus: 1,
		status: "READ",
		folderId: "inbox",
		type: { id: "INTERNAL", name: "Internal" },
		category: { id: "UMUM", name: "UMUM" },
		circulationName: "CC",
		maxResponseDate: null,
		thread: { rootMailId: null, parentMailId: null },
		totalCount: 10,
	},
	{
		id: "mail-3",
		mailNumber: "003/PUB/PR/IV/2026",
		mailDate: "2026-04-13T15:45:00Z",
		subject: "Press Release Launching Fitur Baru",
		audit: {
			createdBy: "user-3",
			createdByName: "Public Relation",
			createdDate: "2026-04-13T15:45:00Z",
			updatedDate: "2026-04-13T15:45:00Z",
		},
		summary: {
			attachmentQty: 2,
			toStr: "Media Partner",
		},
		readStatus: 0,
		status: "DRAFT",
		folderId: "draft",
		type: { id: "INTERNAL", name: "Internal" },
		category: { id: "PUBLIKASI", name: "PUBLIKASI" },
		circulationName: "Disposisi",
		maxResponseDate: "2026-04-20T17:00:00Z",
		thread: { rootMailId: null, parentMailId: null },
		totalCount: 10,
	},
	{
		id: "mail-4",
		mailNumber: "004/ND/IT/IV/2026",
		mailDate: "2026-04-12T09:00:00Z",
		subject: "Maintenance Server Core Banking",
		audit: {
			createdBy: "user-4",
			createdByName: "Manager IT",
			createdDate: "2026-04-12T09:00:00Z",
			updatedDate: "2026-04-12T09:00:00Z",
		},
		summary: {
			attachmentQty: 0,
			toStr: "Seluruh Staff IT",
		},
		readStatus: 1,
		status: "REVISI",
		folderId: "inbox",
		type: { id: "INTERNAL", name: "Internal" },
		category: { id: "ND", name: "Nota Dinas" },
		circulationName: "Disposisi",
		maxResponseDate: "2026-04-20T17:00:00Z",
		thread: { rootMailId: null, parentMailId: null },
		totalCount: 10,
	},
	{
		id: "mail-5",
		mailNumber: "005/U/KEU/IV/2026",
		mailDate: "2026-04-11T11:20:00Z",
		subject: "Revisi Anggaran Triwulan II",
		audit: {
			createdBy: "user-5",
			createdByName: "Manager Keuangan",
			createdDate: "2026-04-11T11:20:00Z",
			updatedDate: "2026-04-11T11:20:00Z",
		},
		summary: {
			attachmentQty: 1,
			toStr: "Para Head of Department",
		},
		readStatus: 0,
		status: "SENT",
		folderId: "inbox",
		type: { id: "INTERNAL", name: "Internal" },
		category: { id: "UMUM", name: "UMUM" },
		circulationName: "Disposisi",
		maxResponseDate: "2026-04-20T17:00:00Z",
		thread: { rootMailId: null, parentMailId: null },
		totalCount: 10,
	},
];

export const DUMMY_MAIL_DETAIL: MailDetailDto = {
	id: "mail-1",
	mailNumber: "001/ND/DIR/IV/2026",
	mailDate: "2026-04-15T08:00:00Z",
	type: { id: "INTERNAL", name: "Internal" },
	category: { id: "ND", name: "Nota Dinas" },
	subject: "Undangan Rapat Koordinasi Bulanan April",
	content: `
		<p>Yth. Para Manager,</p>
		<p>Mengharap kehadiran Bapak/Ibu dalam rapat koordinasi bulanan yang akan dilaksanakan pada:</p>
		<ul>
			<li>Hari/Tanggal: Senin, 20 April 2026</li>
			<li>Waktu: 09.00 WIB - Selesai</li>
			<li>Tempat: Ruang Rapat Utama Lt. 3</li>
			<li>Agenda: Pembahasan Progres Program Kerja Triwulan I</li>
		</ul>
		<p>Demikian undangan ini kami sampaikan, atas kehadirannya diucapkan terima kasih.</p>
		<br/>
		<p>Hormat kami,</p>
		<p><b>Sekretaris Direksi</b></p>
	`,
	note: "Mohon konfirmasi kehadiran paling lambat Jumat ini.",
	maxResponseDate: "2026-04-18T17:00:00Z",
	status: "SENT",
	thread: { rootMailId: null, parentMailId: null },
	summary: {
		attachmentQty: 1,
		toStr: "Para Manager",
	},
	audit: {
		createdBy: "user-1",
		createdByName: "Sekretaris Direksi",
		createdDate: "2026-04-15T08:00:00Z",
		updatedDate: "2026-04-15T08:00:00Z",
	},
	noSuratMasuk: null,
	asalSuratMasuk: null,
	tglSuratMasuk: null,
	tujuanSuratKeluar: "Para Manager",
	penerimaSuratKeluar: "Para Manager",
	circulationName: "Disposisi",
};

export const DUMMY_COUNTERS: FolderCounterDto[] = DUMMY_FOLDERS.map((f) => ({
	folderId: f.id,
	folderName: f.name,
	unread: f.unread,
	total: f.total,
}));
